language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1

before_script:
  - composer self-update
  - composer update

script:
  # run
  - mkdir temp
  - vendor/bin/phpstan analyse -l 7 -c phpstan.neon src tests
  - vendor/bin/phpunit --configuration tests/phpunit.xml tests

after_script:
  # upload clover.xml file to Scrutinizer to analyze it
  - |
    wget https://scrutinizer-ci.com/ocular.phar
    php ocular.phar code-coverage:upload --format=php-clover tests/temp/clover.xml
